### ISSUE TITLE
reportes -> cuenta corriente

### ISSUE THREAD

**Issue by androetto** [pos-cloud/app-web#364]
Necesitamos refactorizar hoy las cuentas tienen muchos registros. 

- Implementar un paginator y por defecto lleve a la ultima pagina y mostrar los ultimos registros
- Hace consulta para obtener el total

**Comment by loana-dev** [comment]
- [ ] la columna Saldo Doc, solo debe decir Saldo. 

 - [ ] no aparecen todos los importes iguales en las columnas D y H, aunque se llega al saldo de igual manera.  ej cliente colautti gabriel, vidal Gerónimo (Bardo) 
 
- [ ]  Crear una nueva transacción.

- [ ]  Imprimir (crear controlador para enviarle todos los datos a api-print).

- [ ]  Poder enviar por correo (modal para que el cliente pueda escribir algo en el body) (mismo endpoint para imprimir).

**Comment by loana-dev** [comment]
- [ ] Aparece en la primer página, debería de aparecer directamente en la última.
